### ISSUE TITLE
Not compatible with Android 12

### ISSUE THREAD

**Issue by cvalcke** [NordicID/nur_tools_rfiddemo_android#2]
This application seems not to be compatible with android 12. No usb device was detected (tested on samsung galaxy tab a7) and no authorisation popin is raised 
Permissions management has changed and it may be related to this

**Comment by hehannul** [comment]
What kind of environment is used that is not working?

I tested with my environment and didn't get any errors. Maybe I have not noticed something?

I used OnePlus Nord CE 3 Lite 5G with Android 13 for testing.
I used Android Studio for building the code.

1= I installed latest Nordic ID RFID Demo from Google Play and it works without errores.
2) I build nur_tools_rfiddemo_android code and tested and it works without errors.
3) I used latest NurApi and NurApiAndroid (API 33 compiled) and it works without errors.

I set OTG connection emabled, and allow all permission when prompted. 
I set that Nordic ID RF Demo is openend, when USB device is connected.
Attaching reader to USB and detaching reader from USB is shiwn in RFID demo statusbar correctly.

Is this issue still valid?

**Comment by hehannul** [comment]
Tested with OnePlus Nord CE 3 Lite 5G (Android 13) and works.
Used Stix reader for testing.

What reader is used,?

**Comment by hehannul** [comment]
I have tested it wrongly and that's reason why it was working in my envrionment.
USB connection is fixed in NurApiAndroid v.2.0.50 and after that fix, USB connection can be made without errors.
Tested with NurApiAndroid v.20.50, Adnroid 13 device (OnePlus= and Stix

Please use v1.91 for Android 12 or higher

**Comment by hehannul** [comment]
Bug fixed in NurApiAndroid v.2.0.50. Use RFID Demo v1.9.1 which contains this fix.
Tested with latest fixes in Android 13 with Stix => wrokds
